### ISSUE TITLE
Export to .exe

### ISSUE THREAD

**Issue by zeeshanjan82** [jaeh/node-webkit-express#2]
How can we export the application to a .exe file.

**Comment by jaeh** [comment]
This link should answer your question, you will have to customize the windows build.bat file though:
https://github.com/nwjs/nw.js/wiki/Application-auto-building-scripts-for-Linux-Windows-and-OSX

i do not use windows so i have no idea if this will work.

express will be started in the same thread as node-webkit, so i assume that just building an exe as described in the nw documentation will work.

**Comment by zeeshanjan82** [comment]
thanks @jaeh  will try the link however I was able to fix the issue using nw.exe so I will close the issue for now.
